---
title: "PICRUSt Data"
output:
    flexdashboard::flex_dashboard:
        navbar:
            - { title: "About Fast Food Study", 
                href: "../../website/_site/index.html", 
                align: left }
        source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning =F, error = F, message=F)
```

```{r, packages}
pkgs = c('plyr', 'dplyr','stringr','reshape2','tibble', 'DT','data.table',
         'limma')
for(pkg in pkgs){
    library(pkg, quietly=TRUE, verbose=FALSE, warn.conflicts=FALSE, 
            character.only=TRUE)
}
```

```{r}
load("../Rdata/mcb_picrust.Rdata")
```

Level 1
=====================================

###

```{r}
picrust$level1 %>%
    t %>% as.data.frame %>%
    datatable(
        extensions = 'Buttons',
        options = list(
            dom = "Bfrtip",
            pageLength = 40,
            bottons = c("copy","csv","excel")
        )
    )
```

Level 2
=====================================

###

```{r}
picrust$level2 %>%
    t %>% as.data.frame %>%
    datatable(
        extensions = 'Buttons',
        options = list(
            dom = "Bfrtip",
            pageLength = 40,
            bottons = c("copy","csv","excel")
        )
    )
```

Level 3
=====================================

###

```{r}
picrust$level3 %>%
    t %>% as.data.frame %>%
    datatable(
        extensions = 'Buttons',
        options = list(
            dom = "Bfrtip",
            pageLength = 40,
            bottons = c("copy","csv","excel")
        )
    )
```
