---
title: "Treatment Diet Nutrient Boxplot"
output:
    flexdashboard::flex_dashboard:
        navbar:
            - { title: "About Fast Food Study", 
                href: "../../website/_site/hdl.html", 
                align: left }
runtime: shiny 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning =F, error = F, message=F)
```

```{r, packages}
pkgs = c('plyr', 'dplyr','stringr','reshape2','plotly', 
         "data.table",'ggplot2', 'ggsci')
for(pkg in pkgs){
    library(pkg, quietly=TRUE, verbose=FALSE, warn.conflicts=FALSE, 
            character.only=TRUE)
}
```

```{r}
# rm(list=ls())
# setwd('/Users/chenghaozhu/Box Sync/UC Davis/Right Now/Researches/Zivkovic Lab/Fast Food Study/Data/between_assays_analysis/hdl_structure_and_function/')
load("../../data/hdl_structure_and_function.Rdata")
pdata = lipidome$pdata
```

###

```{r}
df = data.frame(
    sat_fat = diet_data$`SatFat (g)`,
    mono_fat = diet_data$`MonoFat (g)`,
    poly_fat = diet_data$`PolyFat (g)`,
    fiber = diet_data$`Fib (g)`,
    Subj = pdata$Subj,
    TX = pdata$TX,
    Day = pdata$Day
) %>%
    melt(id.var = (c("Subj","TX","Day")),
         variable.name = "Nutr",
         value.name = "Value") %>%
    mutate(
        Nutr = factor(Nutr, 
                       levels = c("sat_fat","mono_fat","poly_fat","fiber"),
                       labels = c("Sat Fat", "Mono Fat", "Poly Fat", "Fiber"))
    ) %>%
    filter(Day=="Post")
y.upper.limit = diff(range(df$Value)) * 0.05 + max(df$Value)
y.lower.limit = min(df$Value) - diff(range(df$Value)) * 0.05

(ggplot(df, aes(TX,Value)) +
    stat_boxplot(geom = "errorbar", width = 0.5) +
    geom_boxplot(aes(fill = TX)) +
    geom_hline(yintercept = y.upper.limit)+
    scale_y_continuous(labels = function(x){paste(x, "-")},    
                       sec.axis = dup_axis(breaks = 0),
                       expand = c(0, 0)) +
    facet_wrap(~Nutr, nrow=1, strip.position = "bottom") +
    coord_cartesian(ylim = c(y.lower.limit, y.upper.limit)) +
    scale_fill_npg() +
    theme_bw() +
    labs(x = "",
         y = "") +
    theme(
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        #axis.title.y = element_text(size = rel(1.25)),
        axis.title.y.right = element_blank(),
        axis.text.y.right = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_text(margin = margin(r=0)),
        strip.text = element_text(size = rel(1.25)),
        strip.background = element_blank(),
        panel.spacing = unit(0, "mm")
    ) )%>%
    ggplotly

```
