---
title: "Dietary Nutrient Boxplot"
output:
    flexdashboard::flex_dashboard:
        navbar:
            - { title: "About Fast Food Study", 
                href: "../../website/_site/hdl.html", 
                align: left }
        orientation: row
        source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning =F, error = F, message=F)
```

```{r, packages}
pkgs = c('plyr', 'dplyr','stringr','reshape2','tibble', 'plotly', 'DT','data.table',
         'limma','ggthemes','ggplot2','ggsci')
for(pkg in pkgs){
    library(pkg, quietly=TRUE, verbose=FALSE, warn.conflicts=FALSE, 
            character.only=TRUE)
}
```

```{r}
# rm(list=ls())
# setwd('/Users/chenghaozhu/Box Sync/UC Davis/Right Now/Researches/Zivkovic Lab/Fast Food Study/Data/between_assays_analysis/hdl_structure_and_function/')
load('../../data/hdl_structure_and_function.Rdata')
diet_data = diet_data[,c(7,8,9,10,12,13,14,15,16,17,18,29,30,31,32,33,34)]
pdata = lipidome$pdata
```

```{r}
inputPanel(
    selectInput("var", "Select a Nutr Variable",
                choices = names(diet_data), selected = "SatFat (g)")
)
```

### 

```{r}
renderPlotly({
    df = data.frame(
        diet_var = diet_data[,input$var] ,
        Subj = pdata$Subj,
        TX = pdata$TX,
        Day = pdata$Day
    ) 
    df = df %>%
        filter(!is.na(diet_var)) %>%
        mutate(
            Timepoint = ifelse(Day == "Pre", "Baseline", as.character(TX))
        ) %>%
        select(-c(TX,Day))
    p = ggplot(df, aes(Timepoint, diet_var)) +
        geom_boxplot() +
        geom_point(aes(color=Subj)) +
        geom_line(aes(group=Subj, colour=Subj)) +
        scale_color_npg() +
        labs(title = input$var) +
        theme_bw() +
        theme(
            legend.position = "none",
            axis.title = element_blank()
        )
    ggplotly(p)
})
```

### 

```{r}
renderPlotly({
    df = data.frame(
        diet_var = diet_data[,input$var]/diet_data$`Cals (kcal)` ,
        Subj = pdata$Subj,
        TX = pdata$TX,
        Day = pdata$Day
    ) 
    df = df %>%
        filter(!is.na(diet_var)) %>%
        mutate(
            Timepoint = ifelse(Day == "Pre", "Baseline", as.character(TX))
        ) %>%
        select(-c(TX,Day))
    p = ggplot(df, aes(Timepoint, diet_var)) +
        geom_boxplot() +
        geom_point(aes(color=Subj)) +
        geom_line(aes(group=Subj, colour=Subj)) +
        scale_color_npg() +
        labs(title = str_c(input$var, " Normalized by Total Cals")) +
        theme_bw() +
        theme(
            legend.position = "none",
            axis.title = element_blank()
        )
    ggplotly(p)
})
```
