---
title: "Glycan vs HDL Functions Correlation Heatmap"
output:
    flexdashboard::flex_dashboard:
        navbar:
            - { title: "About Fast Food Study", 
                href: "../../website/_site/hdl.html", 
                align: left }
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning =F, error = F, message=F)
```

```{r, packages}
pkgs = c('plyr', 'dplyr','stringr','reshape2','tibble', 'plotly', 'DT','data.table',
         'limma','ggthemes','ggplot2','ggthemr', 'heatmaply',"shiny")
for(pkg in pkgs){
    library(pkg, quietly=TRUE, verbose=FALSE, warn.conflicts=FALSE, 
            character.only=TRUE)
}
```

```{r}
# rm(list=ls())
# setwd('/Users/chenghaozhu/Box Sync/UC Davis/Right Now/Researches/Zivkovic Lab/Fast Food Study/Data/between_assays_analysis/hdl_structure_and_function/')
load('../Rdata/glc_precalc.Rdata')
edata = glycopeptide$glycans$edata
pdata = glycopeptide$glycans$pdata
fdata = glycopeptide$glycans$fdata
```

```{r}
heatmap_data = data.frame(
    glycan = rownames(fdata),
    Protein = fdata$Protein,
    Site = fdata$Site,
    Composition = fdata$`Composition (Hex HexNAc Fuc Sia)`,
    Chol_Efflux = clinical_corr$glycans$`HDL Cholesterol Efflux (mo, %)`$pearson.r,
    TNFa = clinical_corr$glycans$`TNF-a (pg/mL)`$pearson.r,
    Chol_Efflux_P = clinical_corr$glycans$`HDL Cholesterol Efflux (mo, %)`$pearson.pvalue,
    TNFa_P = clinical_corr$glycans$`TNF-a (pg/mL)`$pearson.pvalue
) %>% 
    filter(Chol_Efflux_P<=0.05 | TNFa_P <= 0.05) %>%
    arrange(Protein, Site, Composition) %>%
    column_to_rownames("glycan")
```

Column
---------------------------------

### heatmap

```{r}
heatmaply(heatmap_data[,4:5], colors = Spectral, Rowv = F, Colv = F,
          column_text_angle = 0)
```

```{r}
click_data = reactive({event_data(event = "plotly_click")})
feature = reactive({
    rownames(heatmap_data)[nrow(heatmap_data)+ 1 - click_data()[1,"y"]]
})
fct = reactive({
    c("HDL Cholesterol Efflux (mo, %)","TNF-a (pg/mL)")[click_data()[1,"x"]]
})
```

Column
--------------------------------

###

```{r}
renderPlotly({
    df = data.frame(
        glycan = as.numeric(edata[feature(),]),
        Subj = pdata$Subj,
        Day = pdata$Day,
        TX = pdata$TX
    )
    p = ggplot(df, aes(Day, glycan)) +
        geom_boxplot() +
        geom_point(aes(colour = Subj), size=3) +
        geom_line(aes(group = Subj, colour = Subj)) +
        facet_grid(.~TX) +
        labs(x= "", y="",
             title = str_c(
                 feature(),
                 "  P=", 
                 round(limma_result$glycans[feature(),"P.Value"],3))) +
        theme_hc()+
        scale_color_hc() +
        theme(
            legend.position = "none"
        )
    ggplotly(p)
})
```

###

```{r}
renderPlotly({
    df = data.frame(
        glycan = as.numeric(edata[feature(),]),
        fct = clinical_data[,fct()],
        Subj = pdata$Subj,
        Day = pdata$Day,
        TX = pdata$TX
    )
    p = ggplot(df, aes(glycan, fct)) +
        geom_point(aes(colour = Subj), size = rel(2)) +
        stat_smooth(method = "lm") +
        labs(
            x=feature(),
            y=fct(),
            title = str_c(
                "P=",
                round(clinical_corr$glycans[[fct()]][feature(),"pearson.pvalue"], 3),
                ",  r=",
                round(clinical_corr$glycans[[fct()]][feature(), "pearson.r"],3)
            )
        )+
        theme_bw() +
        scale_color_hc() +
        theme(
            legend.position = "none"
        )
    ggplotly(p)
})

```
