---
title: "Glycopeptides vs HDL Function Scatterplot"
output: 
    flexdashboard::flex_dashboard:
        navbar:
            - { title: "About Fast Food Study", 
                href: "../../website/_site/hdl.html", 
                align: left }
runtime: shiny 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning =F, error = F, message=F)
```

```{r, packages}
pkgs = c('plyr', 'dplyr','stringr','reshape2','tibble', 'plotly', "DT", 
         "data.table",'ggthemes','ggplot2','ggthemr','RColorBrewer',"matrixStats")
for(pkg in pkgs){
    library(pkg, quietly=TRUE, verbose=FALSE, warn.conflicts=FALSE, 
            character.only=TRUE)
}
```

```{r}
# rm(list=ls())
# setwd('/Users/chenghaozhu/Box Sync/UC Davis/Right Now/Researches/Zivkovic Lab/Fast Food Study/Data/between_assays_analysis/hdl_structure_and_function')
load('../Rdata/glc_precalc.Rdata')
fct_data = clinical_data[,c(5,6,17,18,20)]
pdata = glycopeptide$peptides$pdata
```

```{r}
inputPanel(
    selectInput("level", 'Peptide or Glycan? ',
                choices = names(glycopeptide), selected = "glycans"),
    selectInput('covar', 'Select An HDL Variable: ',
                choices = names(fct_data), selected=names(fct_data)[1])
)

```

Column
-------------------------------------
    
### Chart 1

```{r}
renderPlotly({
    data = data.frame(
        covar = fct_data[,input$covar],
        Abundance = as.numeric(glycopeptide[[input$level]]$edata[feature_selected(),]),
        Subj = pdata$Subj,
        TX = pdata$TX,
        Day = pdata$Day
    )
    p = ggplot(data, aes(x = Abundance, y = covar)) +
        geom_point(aes(color = Subj, TX=TX, Day=Day), size=rel(2)) +
        stat_smooth(method='lm', formula = y~x) +
        labs(
            x=feature_selected(),
            y=input$covar
        )+
        theme_bw() +
        theme(
            legend.position = "none"
        )
    ggplotly(p, tooltip="all")
})
```

Column {.tabset}
-------------------------------------

### Stats Table

```{r}
stats_table = reactive({
    clinical_corr[[input$level]][[input$covar]] %>%
        setnames(c("pearson.r", "pearson.p", "spearman.r", 
                   "spearman.p", "kendall.t", "kendall.p")) %>% 
        rownames_to_column(var = "Feature") %>%
        arrange(pearson.p)  %>%
        mutate(
            pearson.r = round(pearson.r, digits = 3),
            pearson.p = round(pearson.p, digits = 3),
            spearman.r = round(spearman.r, digits = 3),
            spearman.p = round(spearman.p, digits = 3),
            kendall.t = round(kendall.t, digits = 3),
            kendall.p = round(kendall.p, digits = 3)
        ) %>%
        column_to_rownames(var = "Feature")
})
output$stats_table = renderDataTable(
    stats_table(), 
    selection = list(mode = "single", selected = 1),
    server=T
    )
feature_selected = reactive({
    rownames(stats_table())[input$stats_table_rows_selected]
})
dataTableOutput("stats_table")
```
