---
title: "Lipidomics Feature Boxplot"
output:
    flexdashboard::flex_dashboard:
        navbar:
            - { title: "About Fast Food Study", 
                href: "http://18.219.241.137:3838/ffs/website/_site/hdl.html", 
                align: left }
        vertical_layout: scroll
        source: embed
runtime: shiny 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning =F, error = F, message=F)
```

```{r, packages}
pkgs = c('plyr', 'dplyr','stringr','reshape2','tibble', 'data.table',
         'plotly', 'DT', 'limma','ggthemes','ggplot2','ggthemr','VennDiagram')
for(pkg in pkgs){
    library(pkg, quietly=TRUE, verbose=FALSE, warn.conflicts=FALSE, 
            character.only=TRUE)
}
```

```{r}
# rm(list=ls())
# setwd('/Users/chenghaozhu/Box Sync/UC Davis/Right Now/Researches/Zivkovic Lab/Fast Food Study/Data/between_assays_analysis/hdl_structure_and_function/')
load('../Rdata/lpd_precalc.Rdata')
edata = edata_list$species
```

### Differential Abundent

```{r}
get_sig_features = function(data){
    return(rownames(data)[!is.na(data$P.Value) & data$P.Value <= 0.05])
}

Concentration = get_sig_features(limma_list$species$Concentration)
Proportion = get_sig_features(limma_list$species$Proportion)
Normalized = get_sig_features(limma_list$species$`Normalized by Total Protein`)
venn_plot = venn.diagram(
    x = list(Concentration, Proportion, Normalized),
    NULL,
    category.names = c("Concentration", "Proportion", "Normalized by Total Protein"),
    fill = RSkittleBrewer::RSkittleBrewer("tropical")[1:3],
    cex=2,
    cat.cex = 1.25,
    main = "Features with Significant Differnetial Abundence"
)
grid.draw(venn_plot)
```

***

* By taking a simple proportion of each feature, we are able to get a highest number of features that have significant abundence (P<=0.05). Normalizing by total protein is a better solution than directly using concentration, but not as good as proportion.

### Correlation with HDL Cholesterol Efflux

```{r}
get_sig_features = function(data){
    df = data[["HDL Cholesterol Efflux (mo, %)"]]
    return(rownames(df)[!is.na(df$pearson.pvalue) & df$pearson.pvalue <= 0.05])
}
Concentration = get_sig_features(clinical_corr$species$Concentration)
Proportion = get_sig_features(clinical_corr$species$Proportion)
Normalized = get_sig_features(clinical_corr$species$`Normalized by Total Protein`)
venn_plot = venn.diagram(
    x = list(Concentration, Proportion, Normalized),
    NULL,
    category.names = c("Concentration", "Proportion", "Normalized by Total Protein"),
    fill = RSkittleBrewer::RSkittleBrewer("tropical")[1:3],
    cex=2,
    cat.cex = 1.25,
    main = "Features with Significant Differnetial Abundence"
)
grid.draw(venn_plot)
```

### Correlation with TNF-a

```{r}
get_sig_features = function(data){
    df = data[["TNF-a (pg/mL)"]]
    return(rownames(df)[!is.na(df$pearson.pvalue) & df$pearson.pvalue <= 0.05])
}
Concentration = get_sig_features(clinical_corr$species$Concentration)
Proportion = get_sig_features(clinical_corr$species$Proportion)
Normalized = get_sig_features(clinical_corr$species$`Normalized by Total Protein`)
venn_plot = venn.diagram(
    x = list(Concentration, Proportion, Normalized),
    NULL,
    category.names = c("Concentration", "Proportion", "Normalized by Total Protein"),
    fill = RSkittleBrewer::RSkittleBrewer("tropical")[1:3],
    cex=2,
    cat.cex = 1.25,
    main = "Features with Significant Differnetial Abundence"
)
grid.draw(venn_plot)
```
