---
title: "Lipidomics QC"
output:
    flexdashboard::flex_dashboard:
        navbar:
            - { title: "About Fast Food Study", 
                href: "../../website/_site/hdl.html", 
                align: left }
        orientation: columns
runtime: shiny 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning =F, error = F, message=F)
```

```{r, packages}
pkgs = c('plyr', 'dplyr','stringr','reshape2','tibble', 'plotly', 'DT',
         'data.table','limma','ggthemes','ggplot2','ggthemr')
for(pkg in pkgs){
    library(pkg, quietly=TRUE, verbose=FALSE, warn.conflicts=FALSE, 
            character.only=TRUE)
}
```

```{r}
# rm(list=ls())
# setwd('/Users/chenghaozhu/Box Sync/UC Davis/Right Now/Researches/Zivkovic Lab/Fast Food Study/Data/between_assays_analysis/hdl_structure_and_function/')
load('../Rdata/lpd_precalc.Rdata')
```

```{r}
df = data.frame(
    mean = fdata$qc_mean,
    cv = fdata$qc_cv,
    sd = fdata$qc_sd,
    feature = fdata$Annotation,
    class = fdata$class,
    ESI = fdata$ESI,
    mol_wt = fdata$mol_wt
)
```

###

```{r}
(
    ggplot(df, aes(x = log(mean), y = log(sd), colour = class, feature = feature, ESI = ESI, mol_wt = mol_wt)) +
    geom_point(size = 2, alpha = 0.75) +
    scale_color_hc() +
    theme_bw() +
    theme(
        legend.position = "none"
    )
) %>%
    ggplotly()
```

###

```{r}
(
    ggplot(df, aes(x = log(mean), y = cv, colour = class, feature = feature, ESI = ESI, mol_wt = mol_wt)) +
        geom_point(size = 2, alpha = 0.75) +
        geom_hline(yintercept = 0.2, linetype = "dash", colour = "red") +
        scale_color_hc() +
        theme_bw() +
        theme(
            legend.position = "none"
        )
) %>%
    ggplotly()
```



