---
title: "When Subject 116 is Removed"
output:
    flexdashboard::flex_dashboard:
        navbar:
            - { title: "About Fast Food Study", 
                href: "../../website/_site/hdl.html", 
                align: left }
        orientation: rows
        vertical_layout: scroll
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning =F, error = F, message=F)
```

```{r, packages}
pkgs = c('plyr', 'dplyr','stringr','reshape2','tibble', 'data.table', "heatmaply",
         'plotly', 'DT', 'limma','ggthemes','ggplot2','ggsci','VennDiagram')
for(pkg in pkgs){
    library(pkg, quietly=TRUE, verbose=FALSE, warn.conflicts=FALSE, 
            character.only=TRUE)
}
```

```{r}
load("../Rdata/lpd_precalc.Rdata")
```

```{r}
## subset the data, excluding 116
pdata_116 = pdata %>%
    rownames_to_column("sample")%>%
    filter(Subj != 116) %>%
    mutate(Subj = factor(Subj)) %>%
    column_to_rownames("sample")

edata_all = edata_list$species$Proportion
edata_116 = edata_list$species$Proportion[,rownames(pdata_116)]

## run limma on 116 removed data
limma_all = limma_list$species$Proportion

design = model.matrix(data=pdata_116, ~TX + Day + TX*Day + Subj + 1)
runLimma = function(edata, design){
    data = log2(edata+1)
    fit = lmFit(data, design)
    fit_ebayes = eBayes(fit)
    fit_top = topTable(fit_ebayes, coef=12, number = nrow(edata), p.value=12, 
                       sort.by='none')
    return(fit_top)
}
limma_116 = runLimma(edata_116, design)
```

```{r}
edata_sub_all = edata_all %>%
    rownames_to_column("feature") %>%
    filter(limma_all$P.Value <= 0.05) %>%
    column_to_rownames("feature") %>%
    t %>% as.data.frame %>%
    mutate(
        Day = pdata$Day,
        TX = pdata$TX,
        Subj = pdata$Subj
    ) %>% 
    melt(id.vars = c("Subj","TX","Day"),
         variable.name = "Feature",
         value.name = "intensity") %>% 
    dcast(Subj + TX + Feature ~ Day,
          value.var = "intensity") %>% 
    mutate(Diff = Post - Pre) %>%
    select(-c(Pre, Post)) %>%
    dcast(Feature~Subj + TX,
          value.var = "Diff") %>% 
    column_to_rownames("Feature")

edata_sub_116 = edata_116 %>%
    rownames_to_column("feature") %>%
    filter(limma_116$P.Value <= 0.05) %>%
    column_to_rownames("feature") %>%
    t %>% as.data.frame %>%
    mutate(
        Day = pdata_116$Day,
        TX = pdata_116$TX,
        Subj = pdata_116$Subj
    ) %>% 
    melt(id.vars = c("Subj","TX","Day"),
         variable.name = "Feature",
         value.name = "intensity") %>% 
    dcast(Subj + TX + Feature ~ Day,
          value.var = "intensity") %>% 
    mutate(Diff = Post - Pre) %>%
    select(-c(Pre, Post)) %>%
    dcast(Feature~Subj + TX,
          value.var = "Diff") %>% 
    column_to_rownames("Feature")

absolute_scale = function(data){
    apply(data, 1, function(row){
        max = max(row)
        min = min(row)
        return((row-min)/(max-min)-0.5)
    }) %>% t
}
```

Row
--------------------------

###

```{r}
## histogram p value - all lipid
p = ggplot(limma_all) +
    geom_histogram(aes(x=P.Value), colour="white", binwidth = 0.025) +
    geom_vline(xintercept = 0.05, colour="red", linetype = "dashed") +
    labs(title = "P Value (all subjects)") +
    theme_bw() 
ggplotly(p)
```

###

```{r}
## histograme adj p value - all lipid
p = ggplot(limma_all) +
    geom_histogram(aes(x=adj.P.Val), colour="white", binwidth = 0.025) +
    geom_vline(xintercept = 0.05, colour="red", linetype = "dashed") +
    labs(title = "adj P Value (all subjects)") +
    theme_bw() 
ggplotly(p)
```

###

```{r}
pca = log2(edata_sub_all + 1) %>% 
    absolute_scale() %>% t %>%
    prcomp

df = data.frame(
    PC1 = pca$x[,1],
    PC2 = pca$x[,2],
    Subj = str_split(colnames(edata_sub_all),"\\_", simplify = T)[,1],
    TX = str_split(colnames(edata_sub_all),"\\_", simplify = T)[,2]
)
p = ggplot(df, aes(PC1, PC2, Subj=Subj)) +
    geom_point(aes(color=TX), size=3) +
    scale_color_lancet() +
    labs(
        x = str_c("PC1 (", round((pca$sdev / sum(pca$sdev))[1], 3),  ")"),
        y = str_c("PC1 (", round((pca$sdev / sum(pca$sdev))[2], 3),  ")"),
        title = str_c(nrow(edata_sub_all), " Features with P<0.05 (all subjects)") 
    ) +
    theme_bw()
ggplotly(p)
```

Row
--------------------------

###

```{r}
### histogram p value - 116 removed
p = ggplot(limma_116) +
    geom_histogram(aes(x=P.Value), colour="white", binwidth = 0.025) +
    geom_vline(xintercept = 0.05, colour="red", linetype = "dashed") +
    labs(title = "P Value (116 excluded)") +
    theme_bw() 
ggplotly(p)
```

###

```{r}
## histograme adj p value - 116 removed
p = ggplot(limma_116) +
    geom_histogram(aes(x=adj.P.Val), colour="white", binwidth = 0.025) +
    geom_vline(xintercept = 0.05, colour="red", linetype = "dashed") +
    labs(title = "adj P Value (116 excluded)") +
    theme_bw() 
ggplotly(p)
```

###

```{r}
pca = log2(edata_sub_116 + 1) %>% 
    absolute_scale() %>% t %>%
    prcomp

df = data.frame(
    PC1 = pca$x[,1],
    PC2 = pca$x[,2],
    Subj = str_split(colnames(edata_sub_116),"\\_", simplify = T)[,1],
    TX = str_split(colnames(edata_sub_116),"\\_", simplify = T)[,2]
)
p = ggplot(df, aes(PC1, PC2, Subj=Subj)) +
    geom_point(aes(color=TX), size=3) +
    scale_color_lancet() +
    labs(
        x = str_c("PC1 (", round((pca$sdev / sum(pca$sdev))[1], 3),  ")"),
        y = str_c("PC1 (", round((pca$sdev / sum(pca$sdev))[2], 3),  ")"),
        title = str_c(nrow(edata_sub_116), " Features with P<0.05 (116 excluded)") 
    ) +
    theme_bw()
ggplotly(p)
```

Row
--------------------------

###

```{r}
col_side_colors = str_split(colnames(edata_sub_all), "\\_",2, simplify = T)[,2] %>%
    as.data.frame %>%
    setnames("Treatment") %>%
    mutate(rownames = colnames(edata_sub_all)) %>%
    column_to_rownames("rownames")

hpdata = log2(edata_sub_all + 1) %>% 
    absolute_scale()
heatmaply(hpdata, colors = RdBu, col_side_colors = col_side_colors)
```

###

```{r}
col_side_colors = str_split(colnames(edata_sub_116), "\\_",2, simplify = T)[,2] %>%
    as.data.frame %>%
    setnames("Treatment") %>%
    mutate(rownames = colnames(edata_sub_116)) %>%
    column_to_rownames("rownames")

hpdata = log2(edata_sub_116 + 1) %>% 
    absolute_scale()

heatmaply(hpdata, colors = RdBu,col_side_colors = col_side_colors)
```
