---
title: "Lipidomics Unsatuation Boxplot"
output:
    flexdashboard::flex_dashboard:
        navbar:
            - { title: "About Fast Food Study", 
                href: "../../website/_site/hdl.html", 
                align: left }
runtime: shiny 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning =F, error = F, message=F)
```

```{r, packages}
pkgs = c('plyr', 'dplyr','stringr','reshape2','tibble', 'plotly', 'DT',
         'data.table','limma','ggthemes','ggplot2','ggthemr')
for(pkg in pkgs){
    library(pkg, quietly=TRUE, verbose=FALSE, warn.conflicts=FALSE, 
            character.only=TRUE)
}
```

```{r}
# rm(list=ls())
# setwd('/Users/chenghaozhu/Box Sync/UC Davis/Right Now/Researches/Zivkovic Lab/Fast Food Study/Data/between_assays_analysis/hdl_structure_and_function/')
load('../Rdata/lpd_precalc.Rdata')
fct_data = clinical_data[,c(5,6,17,18,20,30,31)]
diet_data = diet_data[,c(1,2,4,5,6,7,8,9,10,11,12,13,14,15,16,17,21,22,23,24,25,26)]
edata = sapply(Unsatuation$edata, function(col) col*18) %>% as.data.frame()
rownames(edata) = rownames(Unsatuation$edata)
Unsatuation$edata = edata
```

Differential Abundance
===================================================

Column
---------------------------------------------------

### Boxplot

```{r}
featureBoxPlotGetDf = function(edata, pdata, feature_id){
    # Construct the data table for plotting
    df = melt(edata[feature_id,], 
              value.name = 'Abundance', 
              variable.name='SampleID') %>% 
        mutate(Subj = pdata$Subj,
               TX = pdata$TX,
               Day = pdata$Day) %>%
        column_to_rownames(var = 'SampleID')
    
    return(df)
}

featureBoxPlot = function(edata, pdata, feature_id){
    # get the data
    df = featureBoxPlotGetDf(edata = edata, pdata=pdata, feature_id = feature_id)

    # make the plot
    g = ggplot(df,aes(x = interaction(Day,TX),y=Abundance)) +
        geom_boxplot() +
        geom_point(aes(colour = Subj), size=3) +
        geom_line(data = df[df$TX=='FF',], 
                  aes(group=Subj, colour=Subj)) +
        geom_line(data = df[df$TX=='Med',], 
                  aes(group=Subj, colour=Subj)) + 
        labs(x = "", y = "",
             title = "Equivalent Double Bonds\nPer 18 Carbon") +
        theme_hc() +
        scale_color_hc() +
        theme(
            panel.background = element_blank(),
            panel.grid = element_blank(),
            plot.title = element_text(size = rel(1.75)),
            axis.title.x = element_blank(),
            axis.text.x = element_text(size=rel(1.5), color = 'black'),
            axis.ticks.x = element_blank(),
            axis.ticks.y = element_blank(),
            legend.position = 'none',
            strip.text = element_text(size=15))
    return(g)
}
```

```{r plot1 featureBoxPlot}
renderPlotly({
    featureBoxPlot(
        Unsatuation$edata, 
        pdata, feature_selected_1()) %>%
        ggplotly
})
```


Column
-------------------------------------

### Stats Table

```{r}
lm_table = Unsatuation$limma %>%
    rownames_to_column("Feature") %>%
    arrange(P.Value) %>%
    mutate(
        logFC = round(logFC, digits = 3),
        AveExpr = round(logFC, digits = 3),
        t = round(t, digits = 3),
        P.Value = round(P.Value, digits = 3),
        adj.P.Val = round(adj.P.Val, digits = 3),
        B = round(B, digits= 3)
    ) %>%
    column_to_rownames("Feature")
    
output$lm_table = renderDataTable(
    lm_table, 
    selection = list(mode = "single", selected = 1),
    server=T
    )
feature_selected_1 = reactive({
    rownames(lm_table)[input$lm_table_rows_selected]
})
dataTableOutput("lm_table")
```

vs HDL Functions
===================================================

```{r}
inputPanel(
    selectInput('fct_var', 'Select An HDL Variable: ',
                choices = names(fct_data), selected=names(fct_data)[1])
)

```

Column
-------------------------------------
    
### Chart 1

```{r}
renderPlotly({
    data = data.frame(
        covar = fct_data[,input$fct_var],
        Abundance = as.numeric(Unsatuation$edata[feature_selected_2(),]),
        Subj = pdata$Subj,
        TX = pdata$TX,
        Day = pdata$Day
    )
    p = ggplot(data, aes(x = Abundance, y = covar)) +
        geom_point(aes(color = Subj, TX=TX, Day=Day), size=rel(2)) +
        stat_smooth(method='lm', formula = y~x) +
        labs(
            x=feature_selected_2(),
            y=input$fct_var
        )+
        theme_bw() +
        theme(
            legend.position = "none"
        )
    ggplotly(p, tooltip="all")
})
```

Column
-------------------------------------

### Stats Table

```{r}
clinical_table = reactive({
    Unsatuation$clinical_corr[[input$fct_var]] %>%
        setnames(c("pearson.r", "pearson.p", "spearman.r", 
                   "spearman.p", "kendall.t", "kendall.p")) %>% 
        rownames_to_column(var = "Feature") %>%
        arrange(pearson.p)  %>%
        mutate(
            pearson.r = round(pearson.r, digits = 3),
            pearson.p = round(pearson.p, digits = 3),
            spearman.r = round(spearman.r, digits = 3),
            spearman.p = round(spearman.p, digits = 3),
            kendall.t = round(kendall.t, digits = 3),
            kendall.p = round(kendall.p, digits = 3)
        ) %>%
        column_to_rownames(var = "Feature")
})
output$clinical_table = renderDataTable(
    clinical_table(), 
    selection = list(mode = "single", selected = 1),
    server=T
    )
feature_selected_2 = reactive({
    rownames(clinical_table())[input$clinical_table_rows_selected]
})
dataTableOutput("clinical_table")
```

vs Diet
===================================================

```{r}
inputPanel(
    selectInput("diet_var","Select a Diet Variable",
                choices = names(diet_data), selected = names(diet_data)[1])
)
```


Column
-------------------------------------
    
### Chart 1

```{r}
renderPlotly({
    data = data.frame(
        Dietary_Value = diet_data[,input$diet_var],
        Abundance = as.numeric(Unsatuation$edata[feature_selected_3(),]),
        Subj = pdata$Subj,
        TX = pdata$TX,
        Day = pdata$Day
    )
    p = ggplot(data, aes(x = Dietary_Value, y = Abundance)) +
        geom_point(aes(color = Subj, TX=TX, Day=Day), size=rel(2)) +
        stat_smooth(method='lm', formula = y~x) +
        labs(
            x=input$diet_var,
            y=feature_selected_3()
        )+
        theme_bw() +
        theme(
            legend.position = "none"
        )
    ggplotly(p, tooltip="all")
})
```

Column
-------------------------------------

### Stats Table

```{r}
diet_table = reactive({
    Unsatuation$diet_corr[[input$diet_var]] %>%
        setnames(c("pearson.r", "pearson.p", "spearman.r", 
                   "spearman.p", "kendall.t", "kendall.p")) %>% 
        rownames_to_column(var = "Feature") %>%
        arrange(pearson.p)  %>%
        mutate(
            pearson.r = round(pearson.r, digits = 3),
            pearson.p = round(pearson.p, digits = 3),
            spearman.r = round(spearman.r, digits = 3),
            spearman.p = round(spearman.p, digits = 3),
            kendall.t = round(kendall.t, digits = 3),
            kendall.p = round(kendall.p, digits = 3)
        ) %>%
        column_to_rownames(var = "Feature")
})
output$diet_table = renderDataTable(
    diet_table(), 
    selection = list(mode = "single", selected = 1),
    server=T
    )
feature_selected_3 = reactive({
    rownames(diet_table())[input$diet_table_rows_selected]
})
dataTableOutput("diet_table")
```
