---
title: "Lipidomics Lipid Classes Boxplot"
output: 
    flexdashboard::flex_dashboard:
        navbar:
            - { title: "About Fast Food Study", 
                href: "../../website/_site/hdl.html", 
                align: left }
runtime: shiny 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning =F, error = F, message=F)
```

```{r, packages}
pkgs = c('plyr', 'dplyr','stringr','reshape2','tibble', 'plotly', 'DT',
         'limma','ggthemes','Biostrings','ggplot2','ggthemr')
for(pkg in pkgs){
    library(pkg, quietly=TRUE, verbose=FALSE, warn.conflicts=FALSE, 
            character.only=TRUE)
}
```

```{r}
# rm(list=ls())
# setwd('/Users/chenghaozhu/Box Sync/UC Davis/Right Now/Researches/Zivkovic Lab/Fast Food Study/Data/between_assays_analysis/hdl_structure_and_function')
load('../Rdata/lpd_precalc.Rdata')
edata_list = edata_list$class
limma_list = limma_list$class
rm(list = c(
    "clinical_corr", "clinical_data", "diet_corr", "diet_data"
))
```

```{r input panel}
inputPanel(
    # the feature name to select
    selectInput("feature", "Select a Feature:",
                choices = rownames(edata_list[[1]]),
                selected = "LPC"),
    selectInput("transform", "Select a Transform:",
                choices = names(edata_list), selected = "conc")
)
```

Column 
-------------------------------------
    
### Boxplot

```{r}
featureBoxPlotGetDf = function(edata, pdata, feature_id){
    # Construct the data table for plotting
    df = melt(edata[feature_id,], 
              value.name = 'Abundance', 
              variable.name='SampleID') %>% 
        mutate(Subj = pdata$Subj,
               TX = pdata$TX,
               Day = pdata$Day) %>%
        column_to_rownames(var = 'SampleID')
    
    return(df)
}

featureBoxPlot = function(edata, pdata, feature_id){
    # get the data
    df = featureBoxPlotGetDf(edata = edata, pdata=pdata, feature_id = feature_id)
    # make the plot
    g = ggplot(df,aes(x = interaction(Day,TX),y=Abundance)) +
        geom_boxplot() +
        geom_point(aes(colour = Subj), size=3) +
        geom_line(data = df[df$TX=='FF',], 
                  aes(group=Subj, colour=Subj)) +
        geom_line(data = df[df$TX=='Med',], 
                  aes(group=Subj, colour=Subj)) + 
        theme_hc() +
        scale_color_hc() +
        theme(
            panel.background = element_blank(),
            panel.grid = element_blank(),
            axis.title.x = element_blank(),
            axis.text.x = element_text(size=rel(1.5), color = 'black'),
            axis.ticks.x = element_blank(),
            axis.ticks.y = element_blank(),
            legend.position = 'none',
            strip.text = element_text(size=15))
    return(g)
}
```

```{r plot1 featureBoxPlot}
renderPlotly({
    featureBoxPlot(
        edata_list[[input$transform]], pdata, input$feature) %>%
        ggplotly
})
```


Column
-------------------------------------

### Stats Table

```{r}
renderDataTable({
    limma_list[[input$transform]] %>%
        rownames_to_column(var = "Feature") %>%
        arrange(P.Value) %>%
        column_to_rownames(var = "Feature") %>%
        datatable() %>%
        formatRound(columns = c("logFC", "t", "P.Value", "adj.P.Val", "B"), 
                    digits = 3)
})
```


