---
title: "Lipidomics Feature Boxplot"
output:
    flexdashboard::flex_dashboard:
        navbar:
            - { title: "About Fast Food Study", 
                href: "../../website/_site/hdl.html", 
                align: left }
runtime: shiny 
---
<style>

span.navbar-brand{
color: red !important;
}

#section-stats-table{
overflow: auto !important
}

</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning =F, error = F, message=F)
```

```{r, packages}
pkgs = c('plyr', 'dplyr','stringr','reshape2','tibble', 'plotly', 'DT',
         'limma','ggplot2','ggsci')
for(pkg in pkgs){
    library(pkg, quietly=TRUE, verbose=FALSE, warn.conflicts=FALSE, 
            character.only=TRUE)
}
```

```{r}
# rm(list=ls())
# setwd('/Users/chenghaozhu/Box Sync/UC Davis/Right Now/Researches/Zivkovic Lab/Fast Food Study/Data/between_assays_analysis/hdl_structure_and_function/')
load('../Rdata/lpd_precalc.Rdata')
```

```{r input panel}
inputPanel(
    selectInput('level', "Select Lipid Class or Species:",
                choices = names(edata_list), selected = "species"),
    selectInput('transform', 'Select a Normalization Method:',
                choices = names(edata_list[[1]]), selected = "conc")
)
```

Column 
-------------------------------------
    
### Boxplot

```{r}
featureBoxPlotGetDf = function(edata, pdata, feature_id){
    # Construct the data table for plotting
    df = melt(edata[feature_id,], 
              value.name = 'Abundance', 
              variable.name='SampleID') %>% 
        mutate(Subj = pdata$Subj,
               TX = pdata$TX,
               Day = pdata$Day) %>%
        column_to_rownames(var = 'SampleID')
    
    return(df)
}

featureBoxPlot = function(edata, pdata, feature_id){
    # get the data
    df = featureBoxPlotGetDf(edata = edata, pdata=pdata, feature_id = feature_id)
    # make the plot
    g = ggplot(df,aes(x = interaction(Day,TX),y=Abundance)) +
        geom_boxplot() +
        geom_point(aes(colour = Subj), size=3) +
        geom_line(data = df[df$TX=='FF',], 
                  aes(group=Subj, colour=Subj)) +
        geom_line(data = df[df$TX=='Med',], 
                  aes(group=Subj, colour=Subj)) + 
        theme_bw() +
        scale_color_npg() +
        theme(
            panel.background = element_blank(),
            panel.grid = element_blank(),
            axis.title.x = element_blank(),
            axis.text.x = element_text(size=rel(1.5), color = 'black'),
            axis.ticks.x = element_blank(),
            axis.ticks.y = element_blank(),
            legend.position = 'none',
            strip.text = element_text(size=15))
    return(g)
}
```

```{r plot1 featureBoxPlot}
renderPlotly({
    featureBoxPlot(
        edata_list[[input$level]][[input$transform]], 
        pdata, feature_selected()) %>%
        ggplotly
})
```


Column
-------------------------------------

### Stats Table

```{r}
stats_table = reactive({
    limma_list[[input$level]][[input$transform]] %>%
        rownames_to_column("Feature") %>%
        arrange(P.Value) %>%
        mutate(
            logFC = round(logFC, digits = 3),
            AveExpr = round(logFC, digits = 3),
            t = round(t, digits = 3),
            P.Value = round(P.Value, digits = 3),
            adj.P.Val = round(adj.P.Val, digits = 3),
            B = round(B, digits= 3)
        )%>%
        column_to_rownames("Feature")
}) 
output$stats_table = renderDataTable(
    stats_table(), 
    selection = list(mode = "single", selected = 1),
    server=T
    )
feature_selected = reactive({
    rownames(stats_table())[input$stats_table_rows_selected]
})
dataTableOutput("stats_table")
```

