---
title: "Microbiome vs Biogenic Amines Scatterplot"
output:
    flexdashboard::flex_dashboard:
        navbar:
            - { title: "About Fast Food Study", href: "../../website/_site/mcb.html", align: left }
        wdsource_code: embed
        css: ../../css/styles.css
runtime: shiny 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning =F, error = F, message=F)
```

```{r, packages}
pkgs = c('plyr', 'dplyr','stringr','reshape2','tibble', 'plotly','data.table',
         'Biostrings','ggplot2','ggsci', "DT", "heatmaply")
for(pkg in pkgs){
    library(pkg, quietly=TRUE, verbose=FALSE, warn.conflicts=FALSE, 
            character.only=TRUE)
}
```

```{r}
load('../Rdata/mcb_precalc.Rdata')
bga_data = biogenic_amines$edata %>%
    mutate(feature = biogenic_amines$fdata$Metabolite_Name) %>%
    remove_rownames() %>%
    column_to_rownames("feature")
```

Scatterplot
==================

```{r}
inputPanel(
    selectInput('normal_1', 'Select A Transform Method: ',
                choices = names(edata_list), selected = names(edata_list)[1]),
    selectInput('level_1','Select A Taxonomy Level: ',
                choices = names(edata_list$reads), selected = "Phylum")
)
```

Column
-------------------------------------
    
### Chart 1

```{r}
renderPlotly({
    df = data.frame(
        bga = as.numeric(bga_data[bga_selector(),]),
        mcb = as.numeric(edata_list[[input$normal_1]][[input$level_1]][feature_selector_1(),]),
        Subj = pdata$StudyID,
        TX = pdata$Treatment,
        Day = pdata$Timepoint
    )
    p = ggplot(df, aes(x = mcb, y = bga)) +
        geom_point(aes(color = Subj, TX=TX, Day=Day), size=2) +
        stat_smooth(method='lm', formula = y~x) +
        labs(
            x=feature_selector_1(),
            y=bga_selector()
        )+
        scale_color_npg() +
        theme_bw() +
        theme(
            legend.position = "none"
        )
    ggplotly(p)
})
```

Column 
-------------------------------------

###

```{r}
another_table = reactive({
    bga_corr[[input$normal_1]][[input$level_1]] %>% 
        sapply(function(data){
            pearson = sum(data$pearson.pvalue <= 0.05)
            spearman = sum(data$spearman.pvalue <= 0.05)
            kendall = sum(data$kendall.pvalue <= 0.05)
            return(c(pearson, spearman, kendall))
        }) %>% t %>% as.data.frame() %>%
        setnames(c("pearson p<0.05","spearman p<0.05","kendall p<0.05")) %>%
        rownames_to_column("bga") %>%
        arrange(desc(`pearson p<0.05`)) %>%
        column_to_rownames("bga")
})
output$another_table = renderDataTable(
    another_table(), 
    selection = list(mode = "single", selected = 1),
    server=T,
    options = list(
        pageLength=5,
        scrollX = "200px",
        scrollY = "200px"
        )
    )
bga_selector = reactive({
    rownames(another_table())[input$another_table_rows_selected]
})
dataTableOutput("another_table")
```

### Stats Table

```{r}
stats_table_1 = reactive({
    bga_corr[[input$normal_1]][[input$level_1]][[bga_selector()]] %>%
        setnames(c("pearson.r", "pearson.p", "spearman.r", 
                   "spearman.p", "kendall.t", "kendall.p")) %>% 
        rownames_to_column(var = "Feature") %>%
        arrange(pearson.p)  %>%
        mutate(
            pearson.r = round(pearson.r, digits = 3),
            pearson.p = round(pearson.p, digits = 3),
            spearman.r = round(spearman.r, digits = 3),
            spearman.p = round(spearman.p, digits = 3),
            kendall.t = round(kendall.t, digits = 3),
            kendall.p = round(kendall.p, digits = 3)
        ) %>%
        column_to_rownames(var = "Feature")
})
output$stats_table_1 = renderDataTable(
    stats_table_1(), 
    selection = list(mode = "single", selected = 1),
    server=T,
    options = list(
        pageLength=5,
        scrollX = "200px",
        scrollY = "200px",
        paging = T
        )
    )
feature_selector_1 = reactive({
    rownames(stats_table_1())[input$stats_table_1_rows_selected]
})
dataTableOutput("stats_table_1")
```

Heatmap
==================

```{r}
inputPanel(
    selectInput('normal_2', 'Select A Transform Method: ',
                choices = names(edata_list), selected = names(edata_list)[1]),
    selectInput('level_2','Select A Taxonomy Level: ',
                choices = names(edata_list$reads), selected = "Phylum")
)
```

Column
------------------

### Heatmap

```{r}
renderPlotly({
    data_sub = bga_corr[[input$normal_2]][[input$level_2]][bga_selector_2()]
    r = sapply(data_sub, function(sub){
        value = sub[,"pearson.r"]
        names(value) = rownames(sub)
        return(value)
    }) %>% as.data.frame()
    p = sapply(data_sub, function(sub){
        value = sub[,"pearson.pvalue"]
        names(value) = rownames(sub)
        return(value)
    }) %>% as.data.frame()
    filter = (as.matrix(p) <=0.05 ) %>%
        apply(1, function(row) sum(row)>0)
    df = r[filter,]
    heatmaply(df, colors = rev(RdBu(256)))
})
```

Column
------------------

### Stats Table

```{r}
stats_table_2 = reactive({
    bga_corr[[input$normal_2]][[input$level_2]] %>% 
        sapply(function(data){
            pearson = sum(data$pearson.pvalue <= 0.05)
            spearman = sum(data$spearman.pvalue <= 0.05)
            kendall = sum(data$kendall.pvalue <= 0.05)
            return(c(pearson, spearman, kendall))
        }) %>% t %>% as.data.frame() %>%
        setnames(c("pearson p<0.05","spearman p<0.05","kendall p<0.05")) %>%
        rownames_to_column("bga") %>%
        arrange(desc(`pearson p<0.05`)) %>%
        column_to_rownames("bga")
})
output$stats_table_2 = renderDataTable(
    stats_table_2(), 
    selection = list(selected = 1),
    server=T
    )
bga_selector_2 = reactive({
    rownames(stats_table_2())[input$stats_table_2_rows_selected]
})
dataTableOutput("stats_table_2")
```
