---
title: "Microbiome Heatmap"
output: 
    flexdashboard::flex_dashboard:
        navbar:
            - { title: "About Fast Food Study", href: "../../website/_site/mcb.html", align: left }
        source_code: embed
runtime: shiny 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning =F, error = F, message=F)
```

```{r, packages}
pkgs = c('dplyr', 'plyr','stringr','reshape2','tibble','plotly', "DT",
         'ggplot2','ggsci',"data.table", "heatmaply")
for(pkg in pkgs){
    library(pkg, quietly=TRUE, verbose=FALSE, warn.conflicts=FALSE, 
            character.only=TRUE)
}
```

```{r}
load("../Rdata/mcb_precalc.Rdata")
```

```{r}
inputPanel(
    selectInput("level", "Select a Taxonomy Level:",
                choices = c(names(fdata), "Feature"),
                selected = "Genus"),
    numericInput("cutoff", "Input a P value cutoff:",
                 value = 0.1, min=0, max=1, step = 0.01)
)

```

###

```{r}
renderPlotly({
    data = edata_list$proportion[[input$level]] %>%
    as.data.frame %>%
    rownames_to_column("Feature") %>%
    filter(Differential_Abundance$limma[[input$level]]$P.Value <= input$cutoff) %>%
    column_to_rownames("Feature") %>%
    t %>% as.data.frame %>%
    mutate(Subj = pdata$StudyID, 
           TX = pdata$Treatment, 
           Day = pdata$Timepoint) %>%
    melt(id.var = c("Subj","TX","Day"),
           variable.name = "Feature", value.name = "Abundance") %>%
    dcast(Feature + Subj + TX ~ Day, value.var = "Abundance") %>% 
    mutate(change = Post - Pre,
           sample = str_c(Subj, TX, sep="")) %>%
    dcast(Feature ~ sample, value.var = "change") %>%
    column_to_rownames("Feature") %>%
    apply(1, function(row) 
        (row-min(row))/ (max(row) - min(row))-0.5) %>%
    t%>% as.data.frame()
    
    col_side_colors = str_sub(names(data), 4,6) %>%
    as.data.frame %>%
    setnames("Treatment") %>%
    mutate(rownames = colnames(data)) %>%
    column_to_rownames("rownames")
    
heatmaply(data, colors = rev(RdBu(256)), col_side_colors = col_side_colors)
})

```
